### ISSUE TITLE
Switch from autotools to CMake

### ISSUE THREAD

**Issue by cknadler** [cknadler/marktab-c#1]
Autotools is a pain. Migrate the build to CMake.

**Comment by cknadler** [comment]
Sticking with autotools for now.

**Comment by russplaysguitar** [comment]
Are you just trying to clean up your issues list, or what?

**Comment by cknadler** [comment]
No, I actually spent a bit of time looking into CMake yesterday (and about 20 other build tools: [article](http://www.scons.org/wiki/SconsVsOtherBuildTools)). I know how autotools works, for the most part, and CMake just really doesn't seem like it will be better or easier in any way for this project. 

The only reason I was looking into it in the first place was that someone mentioned that it was a "more modern" version of autotools, but this was far from true.

**Comment by russplaysguitar** [comment]
Hmm, good to know! autotools ftw

**Comment by cknadler** [comment]
I still don't like it at all. If you find a good alternative (or a real convincing argument for CMake) let me know.

**Comment by russplaysguitar** [comment]
You've seen qmake?

**Comment by cknadler** [comment]
Read about it a bit in that article I linked. Have you used it?

**Comment by russplaysguitar** [comment]
ya, a bit. it generates makefiles for you, which is nice. 

i just read up on scons and it looks promising.

**Comment by cknadler** [comment]
One of the only things I have against scons is that it is primarily hosted on Sourceforge... It could be the best thing since sliced bread but...Sourceforge???...come on now :-1:

**Comment by cknadler** [comment]
I like the fact that it is python though. The thing that turned me off of CMake was the language.

**Comment by russplaysguitar** [comment]
agreed. unfortunately, since github is still relatively new to the open source scene we are going to have to wait a while for legacy projects to catch up with the rest of us.

**Comment by russplaysguitar** [comment]
ya, writing build scripts in python sounds rad

**Comment by russplaysguitar** [comment]
oh it looks like you could use Apache Ant, even though it is usually for Java projects
