### ISSUE TITLE
Add rests to grammar

### ISSUE THREAD

**Issue by cknadler** [cknadler/marktab-c#10]
There should be a token for rests. For instance:

input:

```
(1:5 2:5) r 1:5
```

output:

```
e|-5---5-----------------|
B|-5---------------------|
G|-----------------------|
D|-----------------------|
A|-----------------------|
E|-----------------------|
```

Without the rest:

input:

```
(1:5 2:5) 1:5
```

output:

```
e|-5-5-------------------|
B|-5---------------------|
G|-----------------------|
D|-----------------------|
A|-----------------------|
E|-----------------------|
```

**Comment by russplaysguitar** [comment]
+1 

I was wondering about that. Maybe the "times" syntax could also be used here? Like `r x3`

**Comment by cknadler** [comment]
Yeah.

So there are 4 different types of objects:
- chords
- notes
- transitions
- rests

The `times` syntax will apply to every object besides transitions.

**Comment by cknadler** [comment]
In the grammar now. Closing.
