### ISSUE TITLE
Reorganize files into mtr_ and mt_

### ISSUE THREAD

**Issue by cknadler** [cknadler/marktab-c#14]
Set up file organization so that all files that are not part of the runtime have the prefix `mt_` and all runtime files have the prefix `mtr_`.

This is to clear up confusion with files like `mt_string.h`. There are strings involved in a guitar tab, but this is a simple `string` class.

**Comment by cknadler** [comment]
This is a really bad idea. I started moving everything around and it is just way too confusing to be worth it. 

NEW SOLUTION!

Make a lib directory and throw all non runtime files in there. Simple.

**Comment by russplaysguitar** [comment]
Yeah, I'm not a fan of prefixes at all. If you're prefixing a lot of files, that is a pretty clear indication that those files should be in a sub-directory. If you're prefixing a lot of variable names, that usually means you don't understand how the scoping works in the language you're using (unless the language you're using requires it, in which case you should reconsider your choice of language).

If I had things my way, we'd live in a perfect world without pre or post-fixes.
