### ISSUE TITLE
Add test suite

### ISSUE THREAD

**Issue by russplaysguitar** [cknadler/marktab-c#15]
Where the tests?

**Comment by cknadler** [comment]
I'm writing a testing framework specifically for testing `marktab` (and hkl). It's going to be straight output diff tests. If you have any other suggestions as to a testing framework I should use, I'm all ears. New to this whole `c` thing.

**Comment by russplaysguitar** [comment]
I'm not sure, I've never written unit tests in C.

This looks promising: http://www.opensourcetesting.org/unit_c.php

Seems like Barrett would know this?

**Comment by cknadler** [comment]
I talked to him about unit testing a while ago and we decided against it in [hkl](https://github.com/hkl/hkl). If you find anything compelling though, let me know. 

My testing framework is at [cknadler/rcomp](https://github.com/cknadler/rcomp). I'll hopefully have it done within a week or so. There will be some docs on intended functionality up sooner.

**Comment by cknadler** [comment]
Tests will eventually be at https://github.com/cknadler/marktab-tests
