### ISSUE TITLE
Minimum line length

### ISSUE THREAD

**Issue by russplaysguitar** [cknadler/marktab-c#23]
On the grammer page, it looks like there is a lot of extra space at the end of a tab with only a single note on it. This implies a minimum tab line length. Was this intentional, or a by-product of making the examples on the grammer page easier to read?

**Comment by cknadler** [comment]
The latter. MarkTab shouldn't generate unnecessary blank space in the tab. When I was originally writing the grammar I was copy and pasting an empty tab and filling it in.
