### ISSUE TITLE
Harmonics and multipliers

### ISSUE THREAD

**Issue by cknadler** [cknadler/marktab-c#24]
I've run into some ambiguity in the grammar and need some advice.

Using `x[0-9]+` for multipliers wont work. We need a terminal that isn't being used elsewhere. `x` can also be defined as a symbol, and as a muted string. This makes things impossible to parse, particularly in parsing abreviated riffs: `1:9x3/4`.

My solution is this:
- make `x` a reserved name, not allowing anything to ever be defined as `x`, like `x: (4,5:1)`
- redefine the multiplier as `*`, so `1:9 * 4`
- find a new token for harmonics

The problem is, there are only so many keys on the keyboard. I would like the harmonic symbol to be a special character, but we are running out of those.

My current ideas (not happy with any of them):
- `1:9^`
- `1:9!`
- `1:9**`
- `1:9@`

Alternatively, we could leave the harmonic  as `*` and change the multiplier to some other symbol. 

My current ideas for that:
- `1:9 .4`
- `1:9 &4`
- `1:9 +4`
- `1:9 %4`
- `1:9 !4`

/cc @russplaysguitar

**Comment by cknadler** [comment]
To clarify, the harmonic symbol will stay the same in the output. It will remain `*`. This is one reason to leave the symbol in the grammar as `*`, for consistency.

**Comment by russplaysguitar** [comment]
I thought we had agreed on the multiplier syntax like so: `[1:2 3 4] x4` (enclosing the riff in brackets)?

I think the harmonic symbol should stay the same. The multiplier is a more advanced use-case, so it should carry any burdens of complexity.

**Comment by cknadler** [comment]
Having the `x` mean either a muted string or the beginning of a multiplier leads so some problems with the grammar. I agree that `*` should stay as the harmonic symbol. How about `^` as the multiplier?

**Comment by russplaysguitar** [comment]
Hmm, I see. How about upper-case `X` for multipliers?

**Comment by cknadler** [comment]
That could work, although would be a bit confusing. `x` and upper case `X` look extremely similar. I would rather use a different character. `^` is really starting to grow on me. We aren't using it anywhere else either which is nice.

**Comment by russplaysguitar** [comment]
So we decided (via Skype) to implement two multiplier syntaxes:
1. `\sx\d+` (example: `1:9 x9`). Must include a preceding space, doesn't work within inline string sequences.
2. `\^\d+` (example: `1:9^9`). Useful for embedding multipliers in inline string sequences.

**Comment by cknadler** [comment]
Why wouldn't `x9` work with the shorthand syntax for notes on the same string?

**Comment by russplaysguitar** [comment]
Shoot,  now I'm thinking that it should only work with the brackets again, simple because it looks too ambiguous with mutes. 

Examples:
`1:2 3 x4` (multiplier)
`1:2 3 x 4` (mute)

That just reads too similarly, even though we are using the space to differentiate.

I think we should stick to sequences/chords with multipliers instead:
`[1:2 3] x4` (multiplier)
`1:2 3 x 4` (mute)
`1:2 3x4` (mute)
`1:2 3x 4` (mute)
`1:2 3 x4` (mute)

**Comment by cknadler** [comment]
I'm against having two different tokens that should operate the same but dont. Lets just axe the :bomb: `\sx\d+` :bomb:  operator altogether. Then, we only have one operator for multiplication, `^`, it works everywhere just like you would expect it to, with no additional rules. This is much less confusing.

I understand the argument that `x4` is more straightforward but having all of these extra rules behind it completely defeats the purpose.

**Comment by russplaysguitar** [comment]
Alright, you've convinced me
