### ISSUE TITLE
Multipliers and transitions

### ISSUE THREAD

**Issue by cknadler** [cknadler/marktab-c#26]
Another "how should this work" thread:

When you are using a multiplier on an object and then you follow that immediately with a transition, how should that work?

For example:

```
1:5 ^ 2 / 8
```

I'm assuming, in my current implementation, that this would result in:

```
1:5 1:5 / 1:8
```

/cc @russplaysguitar

**Comment by russplaysguitar** [comment]
I can't think of any other alternative to that, other than an error?

**Comment by cknadler** [comment]
Lets make it work like the example. Leaving open till I make some tests.

**Comment by cknadler** [comment]
I've changed my mind on this. I think you were right originally, this should result in a parse error. I think this falls in the same category as transitions from sequences (#28).

**Comment by russplaysguitar** [comment]
Yeah, an error would be best I think
