### ISSUE TITLE
Definitions

### ISSUE THREAD

**Issue by cknadler** [cknadler/marktab-c#27]
Should we allow for definitions to be place anywhere, or only before the actual tab.

For example:

```
# definitions

1:2 3:4

5:5 6:6
```

or

```
# definitions

1:2 3:4

# definitions

5:5 6:6
```

The first example should definitely be valid but what about the second one? Should definitions be allowed anywhere?

/cc @russplaysguitar

**Comment by cknadler** [comment]
To clarify, by definitions, I mean sequence and chord definitions.

**Comment by russplaysguitar** [comment]
I say anywhere, otherwise it'll result in multiple marktab files for one song (one file per part) OR a bunch of definitions at the top for stuff that isn't relevant for a long time in the song.

**Comment by cknadler** [comment]
Sounds good. Leaving open until tests are written.

**Comment by cknadler** [comment]
On another note, I require definitions to happen on their own line. Is that similar to your implementation?

**Comment by cknadler** [comment]
Same question for printing stings actually.

I require the print symbol to be on its own line.

**Comment by russplaysguitar** [comment]
I don't see a reason why definitions need their own line. I mean, it kinda looks better, but logically I see no problems with same line definitions. Pretty sure it works in the current marktab-coffee.

I haven't implemented the print symbol yet, but that does make sense for it to be on it's own line.
