### ISSUE TITLE
Remove transitions involving sequences

### ISSUE THREAD

**Issue by cknadler** [cknadler/marktab-c#28]
After some thought, I think transitions to or from a sequence should result in a runtime error.

For example...

Standard transitions: (which are valid)

```
1:1 / 1:3
```

```
1:1 / 3
```

```
OpenG: (6:3 5,2,1:2 4,3:0)

OpenG / 1:2
```

Sequence transitions: (which should be **invalid**)

```
1:1 / [1:3 3:1]
```

```
[1:3 3:1] / 1:1
```

I'm invalidating these in the grammar for two major reasons:
- This is an edge case at best and is very confusing. It is difficult to tell if the transition applies (like an operator) to the sequence as a whole, or just to the first element (or something else entirely).
- It, alone, makes parsing much more complex.

**Comment by russplaysguitar** [comment]
Yeah, that sounds good

**Comment by cknadler** [comment]
This is done, tests still need to be written though.

**Comment by russplaysguitar** [comment]
Wrong order! 

1) Tests
2) Code
