### ISSUE TITLE
Transition behavior

### ISSUE THREAD

**Issue by cknadler** [cknadler/marktab-c#29]
Transitions are awesome, but I think the current defined behavior could use some work.

Right now, transitions work by taking the common notes between two objects (either notes or chords) and printing the transition symbol between them. For instance:

```
1:1 / 1:2
```

That is pretty straightforward and awesome. They break down, however, when you want to do anything that doesn't share common notes:

```
1:1 / 2:12
```

This, right now, would result in no transition being printed. This is because there are no shared strings between the two objects.

My solution is this:

Make transitions apply to right object. Transitions describe how you want to transition from a note or chord you are currently playing to a new one. The transition just tells you how to get there. You should be able to hammer on from nothing or slide into a note or chord from nothing.

So, for example:

```
1:1 / (1:3 2:3)
```

Would result in:

```
e |-1-/-3-|
B |---/-3-|
// empty lines
```

**Comment by russplaysguitar** [comment]
Hmm, hammer-ons from "nothing" are actually hammer-ons from fret 0. I'm not sure how you slide up or down into a note from nothing. 

The B string in this doesn't make sense to me:

```
e |-1-/-3-|
B |---/-3-|
// empty lines
```

**Comment by cknadler** [comment]
When you transition between playing two different notes, what if you want to slide into the third fret of the B string but you dont want to actually play any notes before that? Transitioning from one note to another has nothing to do with the first note when you think about it. Its about how you get to play the next one.

The concept of transitions only applying to the common strings of two objects is flawed. Hammering a note should not require you to play a note on that string before you can hammer on. You aren't playing a note on fret 0 before you hammer on. The transition is just modifying how you actually play the note.

**Comment by russplaysguitar** [comment]
"...what if you want to slide into the third fret of the B string but you dont want to actually play any notes before that?"

You still will be sliding from somewhere, whether or not you are playing the note that you are sliding from. The note before the transition provides useful information about where to position your hand on the fretboard when the slide begins. For example, say you're sliding up to the 9th fret. It will sound a lot different when you slide from the 7th fret, the 5th fret, or "from" an open string. Same goes for slide-downs.

Regarding hammer-ons: I can see how it could be confusing to write `0h9` when really you don't want to play the string open before the hammer-on. So in that case, `h9` is more accurate. The same is true for pull-offs. 

I see that bending is in the modifiers section of the grammer doc, but it is more of a transition. Bending absolutely requires the initial note. That is how you start the bend, by plucking the initial note and then bending to the next note. A bend without an initial note sounds the exact same as just playing the second note by itself, so there would be no point in annotating it as a bend.
