### ISSUE TITLE
Idea: maybe use string names instead of numbers?

### ISSUE THREAD

**Issue by russplaysguitar** [cknadler/marktab-c#3]
I get a little dyslexic looking at all the numbers. This would be nicer to read (imo) and save me from having to remember which direction to count the stupid strings:

A:5 A:5 A:7 A:5 D:5 D:4
A:5 A:5 A:7 A:5 D:7 D:5
A:5 A:5 G:5 G:4 D:7 D:5 D:4
G:5 G:5 G:4 D:5 D:7 D:5

**Comment by cknadler** [comment]
I want a way to specify tuning, probably in a config section in the header of the file. That would cause this to fail unless it adapted to the change in tuning. For example:

`Tuning: D A D G B E`

`D:5` becomes ambiguous.

You could name the strings unique characters, such as `D A d G B E` or `E A D G B e` but I feel like this just makes things confusing. This problem will also get harder to deal with for guitars with more than 6 strings.

**Comment by russplaysguitar** [comment]
Point taken. I wouldn't mind using upper/lower, but then if you have 3 using the same tuning, it's over.

Maybe it could support string names in standard tuning only?

**Comment by russplaysguitar** [comment]
BTW, here is my first marktab attempt: https://gist.github.com/3937246

**Comment by cknadler** [comment]
I giggled at the Esomething. I totally agree that the numbers start to look like a wall. I'm definitely open to suggestions to make that prettier.

**Comment by russplaysguitar** [comment]
Well, a picture is worth 1000 words, which is why we have tabs to begin with. 

That being said, I did start to get the hang of marktab after writing that gist and it was nice to be able to "write tab" using a simple text editor without worrying about formatting a bunch of dashes like you would with tab text.

Besides the lettering for standard tuning, I'm not sure what else could be done about the wall.
