### ISSUE TITLE
Compilation fails with -Werror

### ISSUE THREAD

**Issue by hlmtre** [cknadler/marktab-c#32]
[image of failure to build ](http://im.zero9f9.com/6wsV8174.png)

% gcc -v                                                                                                                                  ✹ ✭
Using built-in specs.
Target: i486-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.4.5-8' --with-bugurl=file:///usr/share/doc/gcc-4.4/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.4 --enable-shared --enable-multiarch --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.4 --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-objc-gc --enable-targets=all --with-arch-32=i586 --with-tune=generic --enable-checking=release --build=i486-linux-gnu --host=i486-linux-gnu --target=i486-linux-gnu
Thread model: posix
gcc version 4.4.5 (Debian 4.4.5-8)

% bison --version                                                                                                                     1 ↵ ✹ ✭
bison (GNU Bison) 2.4.1

% flex -V                                                                                                                                 ✹ ✭
flex 2.5.35

autoconf (GNU Autoconf) 2.67

**Comment by cknadler** [comment]
Thanks! I'll look into this.

**Comment by cknadler** [comment]
This seems to be causing the error:

``` c
#define mt_queue_each_val(self, block) { \
    MtQueueNode* node; \
    int queue_pos; \
    void* val; \
    for (queue_pos = 0; queue_pos < self->size; ++queue_pos) { \
      if (queue_pos == 0) node = self->front; else node = node->next; \
      val = node->value; \
      block; \
    } \
  }
```

From `y.tab.y`: https://github.com/cknadler/marktab/blob/master/src/y.tab.y#L296
