### ISSUE TITLE
Handle symbol cycles

### ISSUE THREAD

**Issue by cknadler** [cknadler/marktab-c#34]
An example of a symbol cycle would be:

```
# self reference
Sym1: [Sym1]

# reference cycle
Sym2: [Sym3]
Sym3: [Sym2]
```

**Comment by russplaysguitar** [comment]
Ya that's no good

**Comment by cknadler** [comment]
There is actually an easy solution for this.

### Graphs
- Build a graph of all of the symbols in the symbol table
  - Every symbol has a pointer to each symbol it contains
- Implement an algorithm to find cycles in that graph
  - If any exist, output the symbols involved in the cycle and bail out

**Comment by russplaysguitar** [comment]
Sounds good!
