### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by cknadler** [cknadler/marktab-c#39]
[clar](https://github.com/vmg/clar) seems like the best bet for now.

This is basically a two part ticket. With MarkTab becoming a library, the easiest thing to do is going to be to pull the [marktab-tests](https://github.com/cknadler/marktab-tests) repository into the main repo and remove the submodule.

The next step would be to set up clar tests side by side with RComp tests and get them building on travis.

clar will not replace RComp tests. RComp is just very cumbersome and basically only supports integration tests. The project is at the point that it needs some more fine grain testing.

**Comment by russplaysguitar** [comment]
:+1:

**Comment by cknadler** [comment]
Went with check, stuff works. Done and done.
