### ISSUE TITLE
Idea: support for song parts

### ISSUE THREAD

**Issue by russplaysguitar** [cknadler/marktab-c#4]
It would be nice to be able to write:

Chorus:
Amaj Emaj Dmaj Bmaj

Verse:
....

Bridge:
....

Other random part:
.... (don't mess this part up)

**Comment by cknadler** [comment]
I'm going to leave this out of the current iteration of the grammar but I definitely want a way to have headings for each section of the tab. 

I think simply the `Heading Name:` will work for headings. Comments under the tab, which I think is pretty common, might be a bit harder.

**Comment by russplaysguitar** [comment]
Cool

**Comment by cknadler** [comment]
Better idea, new token:

`=`

In use:

```
= this is a bare string
1:9
```

output: 

```
this is a bare string

e|-9-|
B|---|
G|---|
D|---|
A|---|
E|---|
```

In a later version, markdown support would be a very cool idea. Every line is just passed through a markdown parser.

**Comment by cknadler** [comment]
Yeah, this is definitely going in `0.0.1`. It should work similar to a comment line except instead of being ignored, it is output as is. That way you can format your headers or sections however you want or leave them out altogether.

**Comment by russplaysguitar** [comment]
Cool, how come `=`? On a side note, "Why is anything, anything?"

**Comment by cknadler** [comment]
First thing that came to mind. Easy to change though. You thinking of something different?

**Comment by russplaysguitar** [comment]
Well, in YAML, comments begin with `#`, which would compliment the "settings" in the header?

**Comment by cknadler** [comment]
Ah, this may get a little bit confusing. I've been using some ambiguous words to describe what the `=` symbol.

So, the way I have it defined now:
- `=` : the equivalent of a `puts` statement in ruby
- `#` : same as in ruby, any line, or part of a line, that contains a # is ignored by the parser

**Comment by russplaysguitar** [comment]
ahh right, that makes sense. sounds good to me!

**Comment by cknadler** [comment]
Yeah, I'm trying to keep things straight in the [`grammar.md`](https://github.com/cknadler/marktab/blob/master/docs/grammar.md) file. I'll get it cleaned up an presentable soon.

Feel free to modify it and send me a pull request if you have any modifications.

**Comment by cknadler** [comment]
Closing this, the = token is all we need. It will split up sections.

**Comment by russplaysguitar** [comment]
:cool:
