### ISSUE TITLE
Idea: repetitions

### ISSUE THREAD

**Issue by russplaysguitar** [cknadler/marktab-c#5]
Rather than repeating the lines, it would be nice to be able to write the number of repetitions at the end of the line, like so:

Amaj Dmaj Gmaj x4

**Comment by cknadler** [comment]
Love it. Adding it to the grammar.

**Comment by cknadler** [comment]
After some debate, this has been changed. In the grammar now, the "repetition" or "multiplier" operator is `^`.

So the syntax would look like:

```
Gmaj ^ 4

Amaj Gmaj ^ 4

[Amaj Gmaj] ^ 4
```

Closing now that this is all ironed out.

**Comment by russplaysguitar** [comment]
Hmm, so would `Amaj Gmaj ^ 4` mean that Gmaj is repeated 4 times, or that both are repeated 4 times? I think it should just apply to whatever came right before it.

**Comment by cknadler** [comment]
In my implementation, its left associative. Applies to the nearest sequence, chord, note or rest. So yeah, it would apply just to the `Gmaj` in that case.

Result:

```
Amaj Gmaj Gmaj Gmaj Gmaj
```

**Comment by russplaysguitar** [comment]
Okay good, just making sure.
