### ISSUE TITLE
Rhythm?

### ISSUE THREAD

**Issue by jrd730** [cknadler/marktab-c#51]
Dude, so one thing I noticed about the grammar is it doesn't have support for rhythms, as in all notes are treated as the same length. Sure you could just put rests in everywhere, but that seems like it could be problematic and unintuitive. Just a suggestion, but what if in the input file you could specify lengths of notes/chords with a symbol such as: q (quarter note), h (half note), w (whole note), and so on. And then let the tab generating portion of the program figure out the spacing for you.

**Comment by cknadler** [comment]
I like that idea. In general tabs dont have any regard for time but I do agree that it would be nice to be able to play with the spacing. I think the grammar needs a bit of an overhaul but this will definitely be something I will want to add soon.

One problem I see arising is that if you have to prepend a note or chord with a character and you also want to use a modifier character, that would get a bit confusing, especially if there are different symbols for half and full notes.

For example:

```
1:1h~ h 1:5h*
```

The `h` in particular is a bit ambiguous.

How would it work in your mind?

**Comment by jrd730** [comment]
One way around that problem would be to have the note duration on the front of the note and optional modifiers after the note. This would create a clear separation between note duration and modifier that hopefully would not be ambiguous to the parser. Also if the grammar enforces white space around the h for hammer-ons, the parser would know not to associate it with a note duration.

Another way I have seen durations represented in tab has been to place the duration symbol above the note over the tab lines. Using this method allows you to keep all spacing the same which keeps the tab more compact but still contains all the rhythmic information. Here is an example which perfectly demonstrates this: 
http://www.classtab.org/chopin_op64_no2_waltz_in_cqm_7.txt

**Comment by cknadler** [comment]
I really like the above the tab duration. The nice thing about that tab is that it has measures which are super helpful when you also have note durations.

That would be an amazing thing to implement in Marktab but the majority of tabs I see are actually quite simple. I'm apprehensive of overcomplicating the grammar. I think the ability to represent time signatures is filled by writing straight up sheet music.

I'm definitely torn. I think I want support for this in Marktab but it will make the grammar way more complicated. The only way I would implement it is if it were an optional feature that you could turn on via config options.
