### ISSUE TITLE
Idea: marktab highlighting in IDEs

### ISSUE THREAD

**Issue by russplaysguitar** [cknadler/marktab-c#6]
Maybe string numbers could be colored?
Maybe letters A through G could be differently colored?

**Comment by cknadler** [comment]
I'm planning on writing a vim syntax file for marktab as soon as possible. I'm not that familiar with other editors but I will probably give Sublime highlighting a shot as well if I have spare time.

**Comment by cknadler** [comment]
These will both be in a different repository when I get around to them. Rest assured, it will get done but it wont be located here. Probably `cknadler/vim-marktab` & `cknadler/sublime-marktab`.
