### ISSUE TITLE
Multiple note assignment in chords

### ISSUE THREAD

**Issue by cknadler** [cknadler/marktab-c#7]
Allow for the following syntax:

`Emaj: (5:7 4,3,2:9 1:7)`

That would be equivalent to:

`Emaj: (5:7 4:9 3:9 2:9 1:7)`

**Comment by russplaysguitar** [comment]
+1

**Comment by cknadler** [comment]
This is in the grammar. See [docs/grammar](https://github.com/cknadler/marktab/blob/master/docs/grammar.md) for more information. Closing...
