### ISSUE TITLE
Idea: --watch flag

### ISSUE THREAD

**Issue by russplaysguitar** [cknadler/marktab-c#8]
Not sure if you already have this, but it would be nice to be able to start the generator with a --watch flag so that it watches for changes in a marktab file and regenerate the tab file automatically.

**Comment by cknadler** [comment]
For now it's just going to be `marktab tab.mt` and it will output `tab.txt`. I eventually want to put in support for multiple outputs like HTML and possibly even JSON (for super easy parsing). 

I like the idea, definitely worth looking into.
