### ISSUE TITLE
Add optional config header to grammar

### ISSUE THREAD

**Issue by cknadler** [cknadler/marktab-c#9]
marktab needs an optional header that allows you to configure miscellaneous parts of the tab.

Currently running with the idea preceding each config line with a `#`.

```
# strings: 7
# tuning: B E A D G b e
```

defaults:

```
# strings: 6
# tuning: E A D G B e
```

**Comment by cknadler** [comment]
Another idea for this would be to have `bass` and `guitar` modes for marktab to parse.

`Type: bass` would default to `Strings: 4` and `Tuning: E A D G`.

**Comment by cknadler** [comment]
New take on this issue:

Config header should be YAML:

```
---
strings: 7
tuning: B E A D G b e
import: some_chords.mt
---
```

**Comment by russplaysguitar** [comment]
For easier parsing?

**Comment by cknadler** [comment]
Yes, and it stands out better, to me at least. The `---` is pretty universally YAML while the `#` means comment in ruby. So, in the grammar, I changed `---` to indicate a config header and `#` to be a comment. I'm going to remove the c-style comments as well.

**Comment by cknadler** [comment]
Adding a new config option:

``` ruby
line_length: 80 #default
```

That brings us to:

``` ruby
---
strings: 6
tuning: E A D G B e
import: stdlib.mt
line_length: 80
---
```

**Comment by cknadler** [comment]
For the first implementation of the parser, I have a few changes I want to make to the conf header.

### Strings and Tuning

These two are redundant. By declaring what tuning you are using, you are inherently telling MarkTab how many strings have.

I think that removing the `strings` option altogether is the easiest.

### Import

A stdlib of chords would be awesome, but slightly beyond the scope of the first implementation. For now, I'm leaving this out.

### Revised Conf Options

```
tuning: E A D G B e
line_length:  80
```

Much simpler.

**<3 <3 <3**

**Comment by russplaysguitar** [comment]
:ok_hand:
